version: '3'

services:
  api:
    build: api
    command: python -m flask run --host=0.0.0.0
    volumes:
      - ./api:/api
    ports:
      - 5000:5000
    depends_on:
      - database
    environment:
      - CAMERA_PASSWORD=dev
  database:
    image: redis:5.0.9
    environment:
      - POSTGRES_PASSWORD=dev
